#!/usr/bin/env sh

brew install caskroom/cask/brew-cask

brew tap caskroom/versions
brew tap caskroom/fonts

brew tap facebook/fb

brew tap homebrew/binary
brew tap homebrew/boneyard
brew tap homebrew/devel-only
brew tap homebrew/dupes
brew tap homebrew/fuse
brew tap homebrew/gui
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/tex
brew tap homebrew/versions

brew tap neovim/neovim

brew tap rajatvig/rajat

brew tap xoebus/cloudfoundry
