#!/usr/bin/env sh

brew install git

git config --global user.name "Rajat Vig"
git config --global user.email "rajat.vig@gmail.com"
git config --global core.editor vim
git config --global core.excludesfile "~/.gitignore_global"

git config --global --add gitreview.username "rajatvig"

rm ~/.gitignore_global
ln -s ~/dotfiles/config/gitignore_global ~/.gitignore_global
