#!/bin/sh

# node
brew install nvm node

npm uninstall -g grunt-cli
npm uninstall -g js-beautify
npm uninstall -g tern
npm uninstall -g karma-cli
npm uninstall -g yo
npm uninstall -g bower
npm uninstall -g gulp
npm uninstall -g nodemon
npm uninstall -g generator-hottowel
npm uninstall -g eslint
npm uninstall -g eslint-config-standard
npm uninstall -g eslint-plugin-standard
npm uninstall -g eslint-plugin-promise
npm uninstall -g eslint-plugin-react
npm uninstall -g babel-eslint

# node
npm install -g grunt-cli
npm install -g js-beautify
npm install -g tern
npm install -g karma-cli
npm install -g yo
npm install -g bower
npm install -g gulp
npm install -g nodemon
npm install -g generator-hottowel
npm install -g eslint
npm install -g eslint-config-standard
npm install -g eslint-plugin-standard
npm install -g eslint-plugin-promise
npm install -g eslint-plugin-react
npm install -g babel-eslint
