#!/usr/bin/env sh

export PYENV_ROOT="/usr/local/var/pyenv"
mkdir -p $PYENV_ROOT

brew install pyenv python
eval "$(pyenv init -)"

pip install thefuck
pip install virtualenv
pip install tox

pyenv install 3.6.0

ln -s ~/dotfiles/config/pypirc ~/.pypirc
