#!/usr/bin/env sh

brew install bash

# fish
brew install fish

rm -rf .config/fish
rm -rf .config/fish_plugins

mkdir -p .config/{fish,fish_plugins}

git clone git@github.com:justinmayer/tacklebox.git ~/.config/fish_plugins/tacklebox
git clone git@github.com:justinmayer/tackle.git ~/.config/fish_plugins/tackle
git clone git@github.com:joehillen/to-fish.git ~/.config/fish_plugins/to

git clone git@github.com:rajatvig/fish-brew.git ~/.config/fish_plugins/brew
git clone git@github.com:rajatvig/fish-pyenv.git ~/.config/fish_plugins/pyenv
git clone git@github.com:rajatvig/fish-git.git  ~/.config/fish_plugins/git

ln -s ~/dotfiles/config/fish ~/.config/fish

# zsh
brew install zsh
git clone git@github.com:robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

rm ~/.zshrc*
ln -s ~/dotfiles/config/zshrc ~/.zshrc

# change shell
sudo chsh -s /usr/local/bin/fish `echo $USER`

# tmux
rm ~/.tmux.conf
ln -s ~/dotfiles/config/tmux.conf ~/.tmux.conf

# direnv
rm ~/.direnvrc
ln -s ~/dotfiles/config/direnvrc ~/.direnvrc

# powerline
git clone git@github.com:milkbikis/powerline-shell.git ~/.config/powerline-shell
cd ~/.config/powerline-shell
./install.py
cd ~
ln -s ~/.config/powerline-shell/powerline-shell.py ~/powerline-shell.py
