#!/usr/bin/env sh

# node
brew install node

# node
npm install -g grunt-cli
npm install -g js-beautify
npm install -g tern
npm install -g karma-cli
npm install -g yo
npm install -g bower
npm install -g gulp
npm install -g nodemon
npm install -g generator-hottowel
npm install -g eslint
npm install -g eslint-plugin-angular
