#!/usr/bin/env sh

# node
brew install node nvm

export NODE_VERSION="5.3.0"
export NVM_DIR="/usr/local/var/nvm"
mkdir -p $NVM_DIR

brew list nvm | grep nvm.sh | xargs cat > $NVM_DIR/nvm.sh
nvm install $NODE_VERSION
nvm use $NODE_VERSION

npm uninstall -g grunt-cli
npm uninstall -g js-beautify
npm uninstall -g tern
npm uninstall -g karma-cli
npm uninstall -g yo
npm uninstall -g bower
npm uninstall -g gulp
npm uninstall -g nodemon
npm uninstall -g generator-hottowel
npm uninstall -g eslint
npm uninstall -g eslint-plugin-angular
npm uninstall -g eslint-config-openstack

# node
npm install -g grunt-cli
npm install -g js-beautify
npm install -g tern
npm install -g karma-cli
npm install -g yo
npm install -g bower
npm install -g gulp
npm install -g nodemon
npm install -g generator-hottowel
npm install -g eslint
npm install -g eslint-plugin-angular@0.4.0
npm install -g eslint-config-openstack
