#!/usr/bin/env sh

export PYENV_ROOT="/usr/local/var/pyenv"
mkdir -p $PYENV_ROOT

brew install pyenv
eval "$(pyenv init -)"

pyenv install 2.7.11
pyenv install 3.5.1

ln -s ~/dotfiles/config/pypirc ~/.pypirc
