#!/usr/bin/env sh

brew install bash

# fish
brew install fish

rm -rf .config/fish
mkdir ~/.config
ln -s ~/dotfiles/fish ~/.config/fish

git clone git@github.com:chriskempson/base16-shell.git ~/.config/base16-shell

# zsh
brew install zsh
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

rm ~/.zshrc*
ln -s ~/dotfiles/config/zshrc ~/.zshrc

# change shell
sudo chsh -s /usr/local/bin/fish `echo $USER`

# direnv
rm ~/.direnvrc
ln -s ~/dotfiles/config/direnvrc ~/.direnvrc
