#!/usr/bin/env sh

brew install bash

# fish
brew install fish

rm -rf .config/fish
rm -rf .config/omf

curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish

mkdir ~/.config
ln -s ~/dotfiles/config/omf ~/.config/omf

# zsh
brew install zsh
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

rm ~/.zshrc*
ln -s ~/dotfiles/config/zshrc ~/.zshrc

# change shell
sudo chsh -s /usr/local/bin/fish `echo $USER`

# tmux
rm ~/.tmux.conf
ln -s ~/dotfiles/config/tmux.conf ~/.tmux.conf

# direnv
rm ~/.direnvrc
ln -s ~/dotfiles/config/direnvrc ~/.direnvrc
