#!/usr/bin/env sh

brew cask install atom

rm -rf ~/.atom
mkdir ~/.atom

apm install linter
apm install atom-beautify
apm install atomic-emacs
apm install atom-fuzzy-grep

apm install nuclide

# JS
apm install linter-eslint

# python
apm install autocomplete-python
apm install language-restructuredtext
apm install atom-django

# haskell
apm install language-haskell
# apm install haskell-ghc-mod
# apm install autocomplete-haskell

# rust
apm install language-rust
apm install linter-rust
apm install racer

# elixir
apm install language-elixir
apm install autocomplete-elixir

# erlang
apm install language-erlang
apm install autocomplete-erlang
apm install linter-erlang

# go
apm install go-plus

rm ~/.atom/config.cson
rm ~/.atom/keymap.cson

ln -s ~/dotfiles/config/atom/config.cson ~/.atom/
ln -s ~/dotfiles/config/atom/keymap.cson  ~/.atom/
