#!/usr/bin/env sh

brew cask install atom

rm -rf ~/.atom
mkdir ~/.atom

apm install atom-beautify
apm install atom-django
apm install atom-fuzzy-grep
apm install atomic-emacs
apm install autocomplete-elixir
apm install autocomplete-go
apm install autocomplete-python
apm install autocomplete-swift
apm install build
apm install build-make
apm install builder-go
apm install go-plus
apm install language-babel
apm install language-docker
apm install language-elixir
apm install language-erlang
apm install language-gradle
apm install language-graphql
apm install language-groovy
apm install language-haskell
apm install language-ini
apm install language-ocaml
apm install language-restructuredtext
apm install language-rust
apm install language-swift
apm install language-terraform
apm install language-thrift
apm install linter
apm install linter-docker
apm install linter-erlang
apm install linter-eslint
apm install linter-rust
apm install linter-swiftlint
apm install nuclide
apm install racer

rm ~/.atom/config.cson
rm ~/.atom/keymap.cson

ln -s ~/dotfiles/config/atom/config.cson ~/.atom/
ln -s ~/dotfiles/config/atom/keymap.cson  ~/.atom/
