#!/usr/bin/env sh

brew install emacs
brew cask instal emacs

rm ~/.spacemacs
rm -rf ~/spacemacs

git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d
git clone --recursive https://github.com/rajatvig/spacemacs-config ~/spacemacs

ln -s ~/dotfiles/config/spacemacs/spacemacs.el ~/.spacemacs
