#!/usr/bin/env sh

cd ~
git clone git@github.com:rajatvig/dotfiles.git ~/dotfiles

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

cd ~/dotfiles/scripts

sh ./get.packages

cd ~
