#!/usr/bin/env sh

cd ~
git clone git@github.com:rajatvig/dotfiles.git ~/dotfiles

cd ~/dotfiles/scripts

sh ./get.brew
sh ./get.editors
sh ./get.git
sh ./get.osx
sh ./get.packages
sh ./get.shell
sh ./make.links

cd ~
