#!/usr/bin/env sh

cd ~
git clone git@github.com:rajatvig/dotfiles.git ~/dotfiles

cd ~/dotfiles/scripts

sh ./config.brew
sh ./config.git
sh ./get.shell
sh ./get.python
sh ./get.packages
sh ./get.editors
sh ./config.prefs

cd ~
